db_file: "bot.db"

bot_url: "https://t.me/pocket_bot"

messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизирован. Присылай ссылку, а я её сохраню"
    saved_successfully: "Ссылка успешно сохранена!"
    unknown_command: "я не знаю такой команды"
  errors:
    default: "Произошла неизвестная ошибка"
    invalid_url: "это невалидная ссылка!"
    unauthorized: "ты не авторизирован! Используй команду /start"
    unable_to_save: "не удалось сохранить ссылку. Попробуй ещё раз позже"